# Generated by Django 4.2.7 on 2023-11-02 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacienteID', models.PositiveIntegerField(null=True)),
                ('doctorID', models.PositiveIntegerField(null=True)),
                ('nombrePaciente', models.CharField(max_length=40, null=True)),
                ('nombreMedico', models.CharField(max_length=40, null=True)),
                ('fechaCita', models.DateField(auto_now=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesAltaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPaciente', models.PositiveIntegerField(null=True)),
                ('nombrePaciente', models.CharField(max_length=40)),
                ('nombreMedicoAsignado', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('sintomas', models.CharField(max_length=100, null=True)),
                ('fechaIngreso', models.DateField()),
                ('fechaAlta', models.DateField()),
                ('díasTranscurridos', models.PositiveIntegerField()),
                ('honorariosMédico', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=20)),
                ('sintomas', models.CharField(max_length=100)),
                ('asignadoDoctorId', models.PositiveIntegerField(null=True)),
                ('admitirFecha', models.DateField(auto_now=True)),
                ('estado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('departamento', models.CharField(choices=[('Kinesiología', 'Kinesiología'), ('Oftalmología', 'Oftalmología'), ('Otorrinolaringología', 'Otorrinolaringología')], default='Kinesiología', max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
